//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIPR_FinalProject_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoritePlaylist
    {
        public int FavoriteID { get; set; }
        public int UserID { get; set; }
        public int PlaylistID { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Playlist Playlist { get; set; }
        public virtual User User { get; set; }
    }
}
