//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIPR_FinalProject_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.PlaylistSongs = new HashSet<PlaylistSong>();
            this.Playlists = new HashSet<Playlist>();
        }
    
        public int SongID { get; set; }
        public string Title { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Rating { get; set; }
        public string FilePath { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistSong> PlaylistSongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playlist> Playlists { get; set; }
    }
}
